### ISSUE TITLE
Airplay Issues

### ISSUE THREAD

**Issue by Quintus-s** [Ulrar/hassio-addons#9]
Hi Ulrar,

First, congratulations for your addons. Forked Daapd on Hassio with Spotify is what I aimed for a long time.

After installed it I wanted to test immediately on my 3 Airplay outputs. 

2 of them don't work. I can't connect ('failed to activate' on log) and for the third (Airfoil Satellite on Windows), I can see the connexion (Artwork, music name, and audio modulation)...but no sound.

I'm on a Synology Hassio package...so ARM I presume (=> and Hassio is in Docker on Synology DSM).

Thanks a lot,

A french noob :)

**Comment by Ulrar** [comment]
Hey,

I only received my audiocast yesterday, so I had never tried airplay before that. Turns out you need two udp ports for the airplay device to connect back to forked-daapd, I kind of just assumed it worked roughly the same as chromecast but I guess not.
Without those ports I was having the same issue you're seeing on your third device, it says it's playing but there was no sound.

For the other two the config says some airplay devices might need a password defined in there, my does not but if you're still having issues you might want to look into that. TVs also need to be activated from the web interface, I'm still working on ingress but you can access it directly on port 3689 if needed.

I just pushed a quick fix, can you rebuild and try again ?
Note that you'll need to add those ports to your config file : 
```
airplay_shared
{
        control_port = 3690
        timing_port = 3691
}
```

I'm also french, so welcome :)

**Comment by marecabo** [comment]
Thank you for asking that, Quintus-s and thanks for the solution, Ulrar! I also had the connection-but-no-sound issue with a Hifiberry DAC and Moode on a Pi but did not thought it would come from these missing port definitions as my tests with an Android Airplay receiver app (AirBubble) worked without them.

I'll see if I can figure out some `sed` commands to already set this in the Dockerfile.

**Comment by Quintus-s** [comment]
> Hey,
> 
> I only received my audiocast yesterday, so I had never tried airplay before that. Turns out you need two udp ports for the airplay device to connect back to forked-daapd, I kind of just assumed it worked roughly the same as chromecast but I guess not.
> Without those ports I was having the same issue you're seeing on your third device, it says it's playing but there was no sound.
> 
> For the other two the config says some airplay devices might need a password defined in there, my does not but if you're still having issues you might want to look into that. TVs also need to be activated from the web interface, I'm still working on ingress but you can access it directly on port 3689 if needed.
> 
> I just pushed a quick fix, can you rebuild and try again ?
> Note that you'll need to add those ports to your config file :
> 
> ```
> airplay_shared
> {
>         control_port = 3690
>         timing_port = 3691
> }
> ```
> 
> I'm also french, so welcome :)

Haha! J'en étais sûr. C'est pour ça que j'ai précisé que je l'étais aussi.

Thank you for your quick reply.

Just tried to rebuild and add Airplay settings in config file. For the moment, no changes. 

@marecabo, I also tested on Android device with AirBubble. It works. Good tip!

Once again, thank you for your work. I'm sure it will be perfect

Cheers

**Comment by Ulrar** [comment]
Did you remember to refresh the repo before rebuilding ? Changes to config.json aren't applied if you don't, just make sure you can see the new ports (control and timing) in the config tab, if not you need to refresh the repo and rebuild.

**Comment by Quintus-s** [comment]
Forgot it...

Just removed the repo , restart HA and add it to be sure.

Stay tuned...

Edit: and...it works!!!!

Thank you so much. You rocks, guys.

Cheers

**Comment by Ulrar** [comment]
Great !
Thanks for confirming. With the fix and Marecabo's change to the default config this shouldn't be an issue for any future users, thanks for the report and help on the fix !
